M48
; DRILL file {KiCad 7.0.0} date 西元2023年07月13日 (週四) 20時29分23秒
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-07-13T20:29:23+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.3661Y-4.9331
X3.3661Y-6.8268
X6.6551Y-4.9331
X6.6559Y-6.8268
T0
M30
